name: "Epever solar client2"
description: "Epever solar client 2 für einen 2. Gateway"
version: "1.2.11"
slug: "epever-solar-client2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  server:
    host: '0.0.0.0'
    port: 9999
  mqtt:
    host: 'homeassistant.local'
    port: 1883
    username: 'mqtt'
    password: 'mqtt'
    topic: home/epever-solar2
    debug: false
schema:
  server:
    host: str
    port: int(0,65535)
  mqtt:
    host: str
    port: int(0,65535)
    username: str
    password: password
    topic: str
    debug: bool
